def parse_config(filename):
    config = {}
    with open(filename, 'r') as file:
        for line in file:
            if line.startswith('#') or '=' not in line:
                continue
            key, value = line.strip().split('=', 1)
            config[key] = value.strip('"')
    return config

def generate_rust_module(config, output_filename):
    with open(output_filename, 'w') as file:
        file.write("// config.rs\n// Automatically generated by parse_config.py\n\n")
        for key, value in config.items():
            # Determine the type of the value
            if value.isdigit():
                file.write(f"pub const {key}: i32 = {value};\n")
            else:
                file.write(f"pub const {key}: &str = \"{value}\";\n")

if __name__ == "__main__":
    config = parse_config('./.config')
    generate_rust_module(config, './config.rs')